import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { 
  AlertTriangle, ShieldAlert, CheckCircle, Bell, Clock, 
  UserPlus, Mail, Eye, ShieldCheck, CheckSquare, Search
} from 'lucide-react';
import { useApp, Alert } from '../context/AppContext';

export const AlertCenter: React.FC = () => {
  const { alerts, fetchAlerts, addToast, setActiveCaseId } = useApp();
  const navigate = useNavigate();
  const [filterSeverity, setFilterSeverity] = useState<string>('');
  const [filterStatus, setFilterStatus] = useState<string>('ACTIVE');
  const [searchQuery, setSearchQuery] = useState<string>('');
  
  const [activeAlertsList, setActiveAlertsList] = useState<Alert[]>([]);

  useEffect(() => {
    let result = [...alerts];
    
    if (filterSeverity) {
      result = result.filter(a => a.severity === filterSeverity);
    }
    
    if (filterStatus) {
      result = result.filter(a => a.status === filterStatus);
    }

    if (searchQuery) {
      result = result.filter(a => 
        a.account_number.toLowerCase().includes(searchQuery.toLowerCase()) ||
        a.case_id.toLowerCase().includes(searchQuery.toLowerCase()) ||
        a.title.toLowerCase().includes(searchQuery.toLowerCase())
      );
    }

    setActiveAlertsList(result);
  }, [alerts, filterSeverity, filterStatus, searchQuery]);

  const handleResolve = async (alertId: string) => {
    try {
      const res = await fetch(`/api/alerts/${alertId}/resolve`, { method: 'POST' });
      if (res.ok) {
        addToast("Alert Resolved", "Status modified successfully.", "success");
        fetchAlerts();
      }
    } catch (err) {
      addToast("Error", "Failed to resolve alert.", "error");
    }
  };

  const handleNotifyBank = (account: string, bank: string) => {
    addToast(
      "Bank Notified",
      `Simulation request sent to fraud-desk at ${bank} regarding account ${account}.`,
      "info"
    );
  };

  const handleViewCase = (caseId: string) => {
    setActiveCaseId(caseId);
    navigate(`/cases/${caseId}`);
  };

  return (
    <div className="space-y-6">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h2 className="text-xl font-bold text-navy-950 font-sans">Alert Intelligence Center</h2>
          <p className="text-xs text-slate-500 font-sans mt-0.5">
            Manage risk triggers generated by accounts under surveillance.
          </p>
        </div>

        {/* Filter and search bar */}
        <div className="flex flex-wrap gap-2 text-xs">
          <input
            type="text"
            placeholder="Search Account / Case..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="border border-slate-250 px-2 py-1.5 rounded font-mono focus:outline-none"
          />
          <select 
            value={filterSeverity}
            onChange={(e) => setFilterSeverity(e.target.value)}
            className="border border-slate-250 p-1.5 rounded bg-white focus:outline-none"
          >
            <option value="">ALL SEVERITIES</option>
            <option value="CRITICAL">CRITICAL</option>
            <option value="WARNING">WARNING</option>
            <option value="INFO">INFO</option>
          </select>
          <select 
            value={filterStatus}
            onChange={(e) => setFilterStatus(e.target.value)}
            className="border border-slate-250 p-1.5 rounded bg-white focus:outline-none"
          >
            <option value="ACTIVE">ACTIVE ALERTS</option>
            <option value="RESOLVED">RESOLVED ALERTS</option>
            <option value="">ALL ALERTS</option>
          </select>
        </div>
      </div>

      {/* Alerts listing block */}
      <div className="space-y-4">
        {activeAlertsList.length > 0 ? (
          activeAlertsList.map((alert) => {
            const isCritical = alert.severity === 'CRITICAL';
            
            return (
              <div 
                key={alert.alert_id} 
                className={`p-4 border rounded-lg bg-white shadow-sm flex flex-col md:flex-row justify-between md:items-center gap-4 border-l-4 ${
                  isCritical ? 'border-l-red-600' : 'border-l-amber-500'
                }`}
              >
                
                {/* Alert text profile details */}
                <div className="space-y-1 text-xs">
                  <div className="flex items-center gap-2">
                    <span className={`px-2 py-0.5 rounded text-[9px] font-bold ${
                      isCritical ? 'bg-red-50 text-red-800 border border-red-150' : 'bg-amber-50 text-amber-800 border border-amber-150'
                    }`}>
                      {alert.severity}
                    </span>
                    <span className="font-extrabold text-navy-950 font-sans text-sm">{alert.title}</span>
                    <span className="text-[10px] text-slate-400 font-mono flex items-center gap-0.5">
                      <Clock className="w-3.5 h-3.5" />
                      {new Date(alert.timestamp).toLocaleTimeString('en-IN')} | {new Date(alert.timestamp).toLocaleDateString()}
                    </span>
                  </div>

                  <p className="text-slate-650 max-w-3xl leading-relaxed text-[11px]">{alert.description}</p>
                  
                  <div className="flex flex-wrap gap-4 text-[10px] text-slate-450 pt-1">
                    <div>Case Target: <span className="font-mono font-bold text-slate-700">{alert.case_id}</span></div>
                    <div>Surveillance account: <span className="font-mono font-bold text-slate-700">{alert.account_number}</span></div>
                    <div>Disputed Amount: <span className="font-bold text-slate-800">₹{alert.amount_at_risk.toLocaleString('en-IN')}</span></div>
                    {alert.status === 'RESOLVED' && (
                      <span className="text-emerald-700 font-bold flex items-center gap-0.5">
                        <CheckSquare className="w-3.5 h-3.5" /> Resolved
                      </span>
                    )}
                  </div>
                </div>

                {/* Action buttons */}
                {alert.status === 'ACTIVE' && (
                  <div className="flex flex-wrap md:flex-col gap-1.5 shrink-0 justify-end">
                    <div className="flex gap-1.5">
                      <button 
                        onClick={() => handleViewCase(alert.case_id)}
                        className="px-2.5 py-1.5 bg-slate-50 border border-slate-250 hover:bg-slate-100 rounded text-[10px] font-bold text-slate-700 flex items-center gap-1"
                      >
                        <Eye className="w-3.5 h-3.5" />
                        View Case
                      </button>
                      <button 
                        onClick={() => handleNotifyBank(alert.account_number, 'State Bank of India')}
                        className="px-2.5 py-1.5 bg-slate-50 border border-slate-250 hover:bg-slate-100 rounded text-[10px] font-bold text-slate-700 flex items-center gap-1"
                      >
                        <Mail className="w-3.5 h-3.5" />
                        Notify Bank
                      </button>
                    </div>
                    
                    <button 
                      onClick={() => handleResolve(alert.alert_id)}
                      className="px-2.5 py-1.5 bg-navy-950 hover:bg-navy-800 text-white rounded text-[10px] font-bold flex items-center justify-center gap-1"
                    >
                      <CheckCircle className="w-3.5 h-3.5" />
                      Resolve Alert
                    </button>
                  </div>
                )}

              </div>
            );
          })
        ) : (
          <div className="bg-slate-50 border border-dashed rounded p-12 text-center text-slate-400 text-xs">
            <Bell className="w-8 h-8 mx-auto mb-2 text-slate-350" />
            No active triggers matched selection filters.
          </div>
        )}
      </div>

    </div>
  );
};
export default AlertCenter;
